import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{supabase}from'./lib/supabase';
import{roles,roleById,can,visibleNav}from'./accessControl';
import employeeData from'../data/employees.json';
import{LayoutDashboard,Building2,Users,FileText,ClipboardList,Package,Receipt,CalendarDays,DollarSign,Truck,ShieldCheck,BriefcaseBusiness,UserCog,LogOut,Lock,RefreshCw,Plus,Download}from'lucide-react';
import'./supabase-app.css';

const demoProjects=[{id:'demo-1',project_code:'DEMO-001',name:'Koki Waterfront Apartments',status:'On Track',progress:72,budget:4850000,spent:3478000},{id:'demo-2',project_code:'DEMO-002',name:'Waigani Office Complex',status:'At Risk',progress:48,budget:3200000,spent:1815000}];
const nav=[['Dashboard',LayoutDashboard,'dashboard.view'],['Projects',Building2,'projects.view'],['Customers',Users,'customers.view'],['Quotations',FileText,'quotations.view'],['Jobs & Work Orders',ClipboardList,'jobs.view'],['Inventory',Package,'inventory.view'],['Invoicing',Receipt,'invoices.view'],['Schedule',CalendarDays,'projects.view'],['Budget & Costs',DollarSign,'budget.view'],['Suppliers',Truck,'customers.view'],['Safety',ShieldCheck,'safety.view'],['Employees',Users,'employees.view'],['User Access',UserCog,'users.manage'],['Reports',BriefcaseBusiness,'reports.view']];
const money=n=>new Intl.NumberFormat('en-PG',{style:'currency',currency:'PGK',maximumFractionDigits:0}).format(Number(n||0));

function Logo(){return <div className="logo"><img src="/ej-png-logo.svg"/><div><b>EJ PNG</b><span>LIMITED</span></div></div>}
function Login({onLogin}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();setError('');setBusy(true);if(!supabase){setError('Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel.');setBusy(false);return}const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);else onLogin();setBusy(false)};return <div className="login"><div className="login-left"><Logo/><div><small>EJ PNG LIMITED · MANAGEMENT SYSTEM</small><h1>Build better.<br/>Manage smarter.</h1><p>Secure construction operations, workforce, projects and financial reporting.</p></div><footer>PAPUA NEW GUINEA · EJ PNG LIMITED</footer></div><div className="login-right"><div className="login-card"><Logo/><small>SECURE WORKSPACE</small><h2>Welcome back</h2><p>Sign in with your EJ PNG account.</p><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@ejpng.com"/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?'Signing in…':'Sign in'} <b>→</b></button></form><div className="secure"><Lock size={15}/> Supabase Auth protected</div></div></div></div>}

function App(){const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[page,setPage]=useState('Dashboard'),[error,setError]=useState('');const load=async()=>{if(!supabase){setLoading(false);return}const{data:{session}}=await supabase.auth.getSession();setSession(session);if(session){const{data,error}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();if(error)setError(error.message);else setProfile(data)}setLoading(false)};useEffect(()=>{load();if(!supabase)return;const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(!s){setProfile(null);setPage('Dashboard')}else setTimeout(load,0)});return()=>subscription.unsubscribe()},[]);if(loading)return <div className="loading">Loading EJ PNG Management System…</div>;if(!session)return <Login onLogin={load}/>;if(!profile)return <div className="loading"><p>Your account is authenticated but has no EJ PNG profile.</p><button onClick={load}><RefreshCw size={16}/> Refresh</button></div>;const user={...profile};const allowed=nav.filter(([, ,perm])=>visibleNav(user,perm));const logout=async()=>{await supabase?.auth.signOut()};return <div className="app"><aside><Logo/><div className="company"><small>COMPANY WORKSPACE</small><b>EJ PNG Limited</b><span>Construction Operations</span></div><nav>{allowed.map(([name,I,perm])=><button className={page===name?'active':''} onClick={()=>setPage(name)} key={name}><I size={17}/>{name}</button>)}</nav><div className="account"><div><b>{profile.full_name}</b><span>{roleById(profile.role).name}</span></div><button onClick={logout}><LogOut size={16}/> Sign out</button></div></aside><main><header><div>EJ PNG Limited / <b>{page}</b></div><span className="role">{roleById(profile.role).name}</span></header><section className="content">{error&&<div className="error">{error}</div>}{page==='Dashboard'?<Dashboard user={user}/>:page==='Employees'?<Employees user={user}/>:page==='Projects'?<Projects user={user}/>:page==='Reports'?<Reports/>:page==='User Access'?<Access user={user}/>:<Module name={page}/>}</section></main></div>}

function Dashboard({user}){const[data,setData]=useState({projects:[],employees:0,invoices:0,customers:0});useEffect(()=>{(async()=>{if(!supabase)return;const[p,e,i,c]=await Promise.all([supabase.from('projects').select('id,name,progress,budget,spent,status'),supabase.from('employees').select('id',{count:'exact',head:true}),supabase.from('invoices').select('id',{count:'exact',head:true}),supabase.from('customers').select('id',{count:'exact',head:true})]);setData({projects:p.data||[],employees:e.count||0,invoices:i.count||0,customers:c.count||0})})()},[]);const projects=data.projects.length?data.projects:demoProjects;const total=projects.reduce((a,p)=>a+Number(p.budget||0),0),spent=projects.reduce((a,p)=>a+Number(p.spent||0),0);return <><Title eyebrow="EJ PNG LIMITED · OPERATIONS" title="Good morning, EJ PNG team" text="Live management overview from Supabase."/><div className="metrics"><Metric label="Projects" value={projects.length} sub="Current portfolio"/><Metric label="Portfolio value" value={money(total)} sub="Contract / budget"/><Metric label="Committed costs" value={money(spent)} sub="Project spend"/><Metric label="Employees" value={data.employees||employeeData.employees.length} sub="Workforce"/></div><div className="grid"><section className="card"><h2>Project delivery</h2><p>Live project status and financial position.</p>{projects.map(p=><div className="project" key={p.id}><div><b>{p.name}</b><span>{p.status}</span><div className="bar"><i style={{width:`${p.progress||0}%`}}/></div></div><strong>{p.progress||0}%</strong></div>)}</section><section className="card"><h2>System status</h2><p>Authenticated as <b>{user.full_name}</b>.</p><div className="status"><b>Supabase Auth</b><span>Connected</span></div><div className="status"><b>Role</b><span>{roleById(user.role).name}</span></div><div className="status"><b>Access model</b><span>Role based</span></div></section></div></>}
function Metric({label,value,sub}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Title({eyebrow,title,text,children}){return <div className="title"><div><small>{eyebrow}</small><h1>{title}</h1><p>{text}</p></div>{children}</div>}

function Employees({user}){const[rows,setRows]=useState([]),[q,setQ]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState({employee_id:'',name:'',designation:'',department:'',status:'Active'}),[error,setError]=useState('');const load=async()=>{if(!supabase)return;const{data,error}=await supabase.from('employees').select('*').order('name');if(error)setError(error.message);else setRows(data||[])};useEffect(()=>{load()},[]);const shown=(rows.length?rows:employeeData.employees).filter(e=>`${e.employee_id||e.id||''} ${e.name} ${e.designation||''} ${e.department||''}`.toLowerCase().includes(q.toLowerCase()));const add=async e=>{e.preventDefault();const{error}=await supabase.from('employees').insert(form);if(error)setError(error.message);else{setOpen(false);setForm({employee_id:'',name:'',designation:'',department:'',status:'Active'});load()}};return <><Title eyebrow="EJ PNG LIMITED · PEOPLE" title="Employees" text="Live workforce directory and employee records."><div className="actions"><input placeholder="Search employees…" value={q} onChange={e=>setQ(e.target.value)}/>{can(user,'employees.create')&&<button onClick={()=>setOpen(true)}><Plus size={16}/> Add employee</button>}</div></Title>{error&&<div className="error">{error}</div>}{open&&<div className="modal"><form className="card form" onSubmit={add}><h2>Add employee</h2>{Object.entries(form).map(([k,v])=><label key={k}>{k.replace('_',' ')}<input required={k==='name'} value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<div className="form-actions"><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button>Save employee</button></div></form></div>}<section className="card table"><table><thead><tr><th>Employee ID</th><th>Name</th><th>Designation</th><th>Department</th><th>Hire date</th><th>Status</th></tr></thead><tbody>{shown.map(e=><tr key={e.id||e.employee_id}><td>{e.employee_id||e.id||'—'}</td><td><b>{e.name}</b></td><td>{e.designation||'—'}</td><td>{e.department||'—'}</td><td>{e.hire_date||'—'}</td><td>{e.status||'Active'}</td></tr>)}</tbody></table></section></>}

function Projects({user}){const[rows,setRows]=useState([]),[open,setOpen]=useState(false),[form,setForm]=useState({project_code:'',name:'',status:'On Track',progress:0,budget:0,spent:0}),[error,setError]=useState('');const load=async()=>{const{data,error}=await supabase.from('projects').select('*').order('created_at',{ascending:false});if(error)setError(error.message);else setRows(data||[])};useEffect(()=>{load()},[]);const add=async e=>{e.preventDefault();const{error}=await supabase.from('projects').insert({...form,progress:Number(form.progress),budget:Number(form.budget),spent:Number(form.spent)});if(error)setError(error.message);else{setOpen(false);load()}};const data=rows.length?rows:demoProjects;return <><Title eyebrow="EJ PNG LIMITED · DELIVERY" title="Projects" text="Live projects, budgets and delivery status."><div className="actions">{can(user,'projects.create')&&<button onClick={()=>setOpen(true)}><Plus size={16}/> New project</button>}</div></Title>{error&&<div className="error">{error}</div>}{open&&<div className="modal"><form className="card form" onSubmit={add}><h2>New project</h2>{Object.entries(form).map(([k,v])=><label key={k}>{k.replace('_',' ')}<input required={['project_code','name'].includes(k)} value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<div className="form-actions"><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button>Create project</button></div></form></div>}<section className="card table"><table><thead><tr><th>Project</th><th>Progress</th><th>Budget</th><th>Spent</th><th>Status</th></tr></thead><tbody>{data.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.project_code}</small></td><td>{p.progress||0}%</td><td>{money(p.budget)}</td><td>{money(p.spent)}</td><td>{p.status}</td></tr>)}</tbody></table></section></>}

function Access({user}){const[rows,setRows]=useState([]),[error,setError]=useState('');const load=async()=>{const{data,error}=await supabase.from('profiles').select('id,employee_id,full_name,email,role,status').order('full_name');if(error)setError(error.message);else setRows(data||[])};useEffect(()=>{load()},[]);const change=async(id,role)=>{const{error}=await supabase.from('profiles').update({role}).eq('id',id);if(error)setError(error.message);else load()};if(!can(user,'users.manage'))return <div className="card"><h2>Access denied</h2><p>You do not have permission to manage users.</p></div>;return <><Title eyebrow="EJ PNG LIMITED · SECURITY" title="User Access" text="Manage authenticated users and EJ PNG roles."/>{error&&<div className="error">{error}</div>}<section className="card table"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Permissions</th></tr></thead><tbody>{rows.map(u=><tr key={u.id}><td><b>{u.full_name}</b></td><td>{u.email}</td><td><select value={u.role} onChange={e=>change(u.id,e.target.value)}>{roles.map(r=><option value={r.id}>{r.name}</option>)}</select></td><td>{u.status}</td><td>{roleById(u.role).permissions.includes('*')?'Full system':roleById(u.role).permissions.length}</td></tr>)}</tbody></table></section></>}

function Reports(){const[projects,setProjects]=useState([]);useEffect(()=>{supabase?.from('projects').select('*').then(({data})=>setProjects(data||[]))},[]);const data=projects.length?projects:demoProjects;const download=()=>{const csv=[['Project','Code','Progress','Budget PGK','Spent PGK','Status'],...data.map(p=>[p.name,p.project_code,p.progress,p.budget,p.spent,p.status])].map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='ej-png-project-report.csv';a.click();URL.revokeObjectURL(a.href)};return <><Title eyebrow="EJ PNG LIMITED · REPORTING" title="Reports" text="Exportable management reporting from project data."><div className="actions"><button onClick={download}><Download size={16}/> Export CSV</button></div></Title><section className="card table"><table><thead><tr><th>Project</th><th>Progress</th><th>Budget</th><th>Spent</th><th>Variance</th><th>Status</th></tr></thead><tbody>{data.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{p.progress||0}%</td><td>{money(p.budget)}</td><td>{money(p.spent)}</td><td>{money(Number(p.budget||0)-Number(p.spent||0))}</td><td>{p.status}</td></tr>)}</tbody></table></section></>}
function Module({name}){return <><Title eyebrow="EJ PNG LIMITED · OPERATIONS" title={name} text="This module is protected by the EJ PNG role model."/><section className="card empty"><ShieldCheck size={32}/><h2>{name} workspace</h2><p>The authenticated foundation is connected. The next data table for this module can now be wired directly to Supabase.</p></section></>}

createRoot(document.getElementById('root')).render(<App/>);
